### PR TITLE
Release 2.2 - Improved Fluent DSL, Automatic Step on Failure and Last Step and Documentation

### PR DESCRIPTION
**Pull request by bruderol**
* Improved Fluent DSL (now part of the library, as one optional DSL)
* Automatic Step on Failure and Last Step
* Documentation improved

@xeronimus @dola 
Would be great if you could review that and merge to develop, if you agree on my changes.

I allready use the pre-release from branch `release-2.2` and the new fluent DSL in my current project and it works great :smile: 

Probably the generated API doc is now not yet optimaly reflecting the new changes, I need to see about that.

### CODE REVIEW

**Comment by xeronimus** [comment]
Thx! I'm gonna look into it tomorrow afternoon..

**Comment by xeronimus** [comment]
Did you notice the failed travis build?

**Comment by bruderol** [comment]
@xeronimus yes, I did notice it, but funny, localy I did not encounter any issues... will have a look at it. Thank you for feedback.

**Comment by xeronimus** [comment]
I guess you missed adding rimraf to the package json

Rolf Bruderer <notifications@github.com> schrieb am Do., 14. Apr. 2016,
23:20:

**Comment by xeronimus** [comment]
Hi there,

I replaced "rimraf" with "del", since it was already a dependency. also clean scenarioo output directory ansynchronously.  btw, is there a test for that ?  (new "options" argument and cleaning of a directory.. ? )

I merged into develop, however there are still TODOs for #17 and #18...

**Comment by bruderol** [comment]
hmm, strange, how could I build it and use it in my project without adding the dependency? somehow unbelievable for me. But okay, thank you so much for fixing it!

And thank you for the feedback, I will try to resolve the mentioned open points.

**Comment by xeronimus** [comment]
Quick explanation: you installed rimraf locally without --save
Thus its locally available but not on the travis build server

Rolf Bruderer <notifications@github.com> schrieb am Fr., 15. Apr. 2016,
20:21:

**Comment by bruderol** [comment]
Hmm, strange, that is not how I usually work. But yes, could be, normaly I add libraries to the package.json by hand (just to be sure I not forget --save and for I can control the version) and then call npm install - dont know why I did not do this this time - sorry for this mistake.

**Pull request merged**
