### PR TITLE
Bugfix and some docu improvements for Release 2.2

### PR DESCRIPTION
**Pull request by bruderol**
fix for new way of jasmine reporting disabled specs

### CODE REVIEW

**Comment by bruderol** [comment]
@adiherzog @dola please review, thanks.

**Comment by bruderol** [comment]
@adiherzog @dola Can please somebody review and merge?

**Comment by bruderol** [comment]
and please take care to not remove the branch after merge
(RC is still the release branch)

**Comment by bruderol** [comment]
Ok, since nobody reviewed, I megre now. @dola would be nice if you can review and merge my changes from time to time.

**Comment by bruderol** [comment]
@adiherzog you reported this bug, did you test whether my fix was successful for you?

**Comment by adiherzog** [comment]
@bruderol No, did not test it. Will test it as soon as we start using Scenairoo in my project.

**Pull request merged**
