### PR TITLE
#38 Migrate content from Wiki to markdown docs

### PR DESCRIPTION
**Pull request by bruderol**
* Moved content from wiki to markdown files in repo
* Reviewed and adjusted/detailed the release process, because I want to release soon ...
* Improved root README.md docu for newest version to be released soon
* introduced and prepared changelog for release
* linked CTD presentation slides

### CODE REVIEW

**Comment by bruderol** [comment]
@adiherzog @dola Maybe someone can review and merge??

**Comment by bruderol** [comment]
@dola Please review and merge!!!

**Comment by dola** [comment]
Will have a look tonight

**Comment by dola** [comment]
Made some minor text changes. You can merge when the build succeeds.

**Pull request merged**
